import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { unstable_getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]";
import { useSession } from "next-auth/react";
import PostCard from "../components/post-card";
import PostInput from "@/components/post-input";

const Home: NextPage = () => {
  const utils = trpc.useContext();

  const posts = trpc.useQuery(["post.getAll"]);
  const { data: session, status } = useSession();

  const mutationToggleLike = trpc.useMutation("post.toggleLike", {
    onSuccess(input) {
      utils.invalidateQueries(["post.getAll"]);
      //   if (!posts) return;
      //   utils.setQueryData(["post.getAll"], (posts) => {
      //     if (!posts) return [];
      //     return posts.map((post) =>
      //       post.id === input.updatedPost?.id
      //         ? { ...post, ...input.updatedPost }
      //         : post
      //     );
      //   });
    },
  });

  const handleToggleLike = async (postId: string) => {
    mutationToggleLike.mutate({ postId: postId });
  };

  // console.log(posts.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto min-h-screen p-4">
        <PostInput />
        <div className="mb-20" />
        <div className="space-y-5">
          {posts.isSuccess &&
            posts.data.map((post) => (
              <PostCard
                key={post.id}
                post={post}
                handleToggleLike={handleToggleLike}
              />
            ))}
        </div>
      </main>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );

  if (!session) {
    return {
      redirect: {
        destination: "/api/auth/signin",
        permanent: false,
      },
    };
  }
  return {
    props: { session },
  };
}

export default Home;
